#
# Corrected and Validated Render Blueprint for Inbox Zero
#

# Defines the managed databases for the application
databases:
  - name: inbox-zero-db
    plan: free
    databaseName: inbox_zero_db
    user: inbox_zero_user

# Defines the services (web app, redis, cron jobs)
services:
  # The main web application (Next.js)
  - type: web
    name: inbox-zero
    env: node
    plan: starter
    buildCommand: |
      pnpm install
      pnpm turbo run build --filter=web
      cd apps/web && pnpm prisma migrate deploy
    startCommand: cd apps/web && pnpm start
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inbox-zero-db
          property: internalConnectionString
      - key: UPSTASH_REDIS_URL
        fromService:
          type: redis
          name: inbox-zero-redis
          property: internalUrl
      - key: UPSTASH_REDIS_TOKEN
        value: from-render-url
      - key: NEXTAUTH_URL
        value: https://inbox-zero.onrender.com # IMPORTANT: Change this if you rename the service
      - key: NEXT_PUBLIC_APP_URL
        value: https://inbox-zero.onrender.com # IMPORTANT: Change this if you rename the service
      # --- Secrets (you will fill these in on the Render dashboard) ---
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: GOOGLE_ENCRYPT_SECRET
        sync: false
      - key: GOOGLE_ENCRYPT_SALT
        sync: false
      - key: GOOGLE_PUBSUB_TOPIC_NAME
        sync: false
      - key: GOOGLE_PUBSUB_VERIFICATION_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: DEFAULT_LLM_PROVIDER
        value: openai
      - key: ADMINS
        sync: false

  # The Redis Instance
  - type: redis
    name: inbox-zero-redis
    plan: free

  # The Cron Jobs
  - type: cron
    name: inbox-zero-watch-all
    schedule: "0 1 * * *"
    command: curl https://inbox-zero.onrender.com/api/google/watch/all

  - type: cron
    name: inbox-zero-summary
    schedule: "0 16 * * 1"
    command: curl https://inbox-zero.onrender.com/api/resend/summary/all

  - type: cron
    name: inbox-zero-disable-drafts
    schedule: "0 3 * * *"
    command: curl https://inbox-zero.onrender.com/api/reply-tracker/disable-unused-auto-draft
