#
# Render Blueprint for Inbox Zero
#
# 1. Fork the Inbox Zero repository.
# 2. Add this render.yaml file to the root of your fork.
# 3. Go to https://dashboard.render.com/blueprints and create a new Blueprint.
# 4. Connect your forked repository.
# 5. Render will prompt you to fill in the secret environment variables.
#

services:
  # -----------------
  # The main web application (Next.js)
  # -----------------
  - type: web
    name: inbox-zero
    env: node
    plan: starter # Use starter or higher; free plan may time out during build.
    buildCommand: |
      pnpm install
      pnpm turbo run build --filter=web
      cd apps/web && pnpm prisma migrate deploy
    startCommand: cd apps/web && pnpm start
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: inbox-zero-db
          property: internalConnectionString
      - key: UPSTASH_REDIS_URL
        fromService:
          type: redis
          name: inbox-zero-redis
          property: internalUrl
      - key: UPSTASH_REDIS_TOKEN
        value: from-render-url # The redis client parses the password from the URL
      - key: NEXTAUTH_URL
        value: https://inbox-zero.onrender.com # IMPORTANT: Change if you rename the service
      - key: NEXT_PUBLIC_APP_URL
        value: https://inbox-zero.onrender.com # IMPORTANT: Change if you rename the service
      # --- Secrets ---
      # You will be prompted to enter these values during blueprint setup.
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: GOOGLE_ENCRYPT_SECRET
        sync: false
      - key: GOOGLE_ENCRYPT_SALT
        sync: false
      - key: GOOGLE_PUBSUB_TOPIC_NAME
        sync: false
      - key: GOOGLE_PUBSUB_VERIFICATION_TOKEN
        sync: false
      - key: OPENAI_API_KEY # or your preferred LLM provider key
        sync: false
      - key: DEFAULT_LLM_PROVIDER
        value: openai # or anthropic, groq, etc.
      - key: ADMINS
        sync: false

  # -----------------
  # The PostgreSQL Database
  # -----------------
  - type: psql
    name: inbox-zero-db
    plan: free # 'free' plan is fine for starting out

  # -----------------
  # The Redis Instance
  # -----------------
  - type: redis
    name: inbox-zero-redis
    plan: free # 'free' plan is fine for starting out

  # -----------------
  # The Cron Jobs
  # -----------------
  - type: cron
    name: inbox-zero-watch-all
    schedule: "0 1 * * *" # At 01:00 AM UTC daily
    command: curl https://inbox-zero.onrender.com/api/google/watch/all

  - type: cron
    name: inbox-zero-summary
    schedule: "0 16 * * 1" # At 04:00 PM UTC every Monday
    command: curl https://inbox-zero.onrender.com/api/resend/summary/all

  - type: cron
    name: inbox-zero-disable-drafts
    schedule: "0 3 * * *" # At 03:00 AM UTC daily
    command: curl https://inbox-zero.onrender.com/api/reply-tracker/disable-unused-auto-draft
